### ISSUE TITLE
[recipe request] r-base

### ISSUE THREAD

**Issue by jayfurmanek** [IBM/powerai#56]
Name of package: r-base
    URL of package source code:  https://cran.r-project.org/src/base/R-3/R-3.4.3.tar.gz
    License of package: GPLv3
    List of package dependencies:

``` 
 build:
    - {{ compiler('c') }}                # [not win]
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('fortran') }}          # [not win]
    - make                               # [not win]
    - {{native}}toolchain                # [win]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libxrender') }}            # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libuuid') }}               # [linux]
    - {{ cdt('libsm-devel') }}           # [linux]
    - {{ cdt('libice-devel') }}          # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxt') }}                 # [linux]
    - {{ cdt('libxt-devel') }}           # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxau') }}                # [linux]
    - {{ cdt('java-1.7.0-openjdk') }}    # [linux]
    - {{posix}}pkg-config
    - llvm-openmp >=4.0.1                # [osx]
    - posix                              # [win]
    - m2-texinfo-tex                     # [win]
    - m2-texinfo                         # [win]
    - m2-curl                            # [win]
    - m2-p7zip                           # [win]
    - texlive-core                       # [unix]
    - {{posix}}autoconf
    - {{posix}}automake-wrapper          # [win]
    - {{posix}}automake                  # [not win]
  host:
    # This is a hack, strong run_exports should cause this to be added
    - llvm-openmp >=4.0.1                # [osx]
    - libgfortran                        # [osx]
    - readline 7.*                       # [not win]
    - ncurses                            # [not win]
    - libcurl                            # [not win]
    - xz                                 # [not win]
    - libpng                             # [not win]
    - {{native}}bzip2 1.0.*
    - {{native}}cairo                    # [not win]
    - {{native}}jpeg                     # [not win]
    - {{native}}glib                     # [linux]
    - {{native}}bwidget
    - {{native}}tktable
    - {{native}}pango 1.42.*             # [not win]
    - {{native}}icu
    - {{native}}pcre
    - {{native}}tk 8.6.*                 # [not win]
    - {{native}}zlib                     # [not win]
    - {{native}}libtiff                  # [not win]
    - {{native}}openblas-devel >=0.2.20  # [linux]

  run:
    - _r-mutex 1.* anacondar_1
    - {{ compiler('c') }}                # [not win]
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('fortran') }}          # [not win]
    - llvm-openmp >=4.0.1                # [osx]
    - readline 7.*                       # [not win]
    - libcurl                            # [not win]
    - curl                               # [not win]
    - {{native}}bwidget
    - {{native}}tktable
    - {{native}}pango 1.*                # [not win]
    - {{native}}pcre
    - {{native}}tk 8.6.*                 # [not win]
```

    Short description of package and use case(s):
'R is a free software environment for statistical computing and graphics.'

Folks who would also like to see this package in the supplementary channel, please thumbs-up so the developers can know which requests to prioritize.
